[package]
name = "day-12"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
divan = "0.1.5"
itertools = "0.12.0"
nom = "7.1.3"
rayon = "1.8.0"


[[bench]]
name = "example"
harness = false
